### ISSUE TITLE
device.js ?

### ISSUE THREAD

**Issue by pf-john-cleve** [mbientlab-projects/cordova-plugin-metawear#3]
Hey Lance,

I sat in on your wearables talk at All Things Open in Raleigh, NC earlier this week. I ordered a metawear Tuesday night and have it in hand today. I'm trying to get your cordova example running and I'm having some difficulty. Your instructions reference a "device.js" asset, but i'm not finding that anywhere. Any ideas?

Thanks,
John Cleve

**Comment by lgleasain** [comment]
Hey John,

That is Awesome!  Are you using an Android of IOS device?  Also,  which board did you buy?

Have a look at this repository https://github.com/mbientlab-projects/metawear_cordova_example .  The file you need in include (after installing the plugin) is Device.js.  I'm also going to update the docs to be more explicit with that.  

Let me know if you have any questions etc.  The functionality is limited right now,  but I'm in the process of adding more functionality so keep an eye on this space for more exciting things.

Lance

**Comment by pf-john-cleve** [comment]
Hey Lance,

Thanks for getting back to me. I'm using my iPhone at the moment, but have an android device also. I bought the "R" model to get started. I've been an arduino nerd for a few years now, so I'm pretty excited to see what I can come up with! Hopefully I'll be able to contribute once I get the hang of the device and the API. 

Thanks for the info and I'll keep an eye on your repo!

John

**Comment by lgleasain** [comment]
Ah,  ok.  The IOS stuff isn't ready yet....  I'm actually in the process of working on that as we speak.  The Android stuff does.  Some key things with using Android.  You need to be on 4.3 or higher and you will need to have a device that has a Bluetooth 4.0 radio.

**Comment by pf-john-cleve** [comment]
I got your example running on a rooted Nexus 7! It get a few errors when trying to connect to the metawear boad, but it eventually connects and I get RSSI and axcel data. Awesome! Thanks again.

**Comment by lgleasain** [comment]
Cool!  👍

**Comment by pf-john-cleve** [comment]
It's a 2012, which doesn't officially support BLE, but you can enable it with a minor hack. As for features, I'm still digging through what code I can find floating around the web, so I don't yet have much in the way of feature suggestions. 

I'm thinking for my first project, I want write a cordova platformer game that uses the accel and gyro for character movement. It's a bit ambitious, but I think I can get it done. I'll be sure to share my progress once I get underway.
